# Production stage
FROM nginx:stable-alpine

# Copy the built artifacts from the local dist folder
COPY dist /usr/share/nginx/html

# Nginx config is mounted via docker-compose volumes

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
